logging:
  level:
    root: INFO
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  datasource:
    username: kudl
    password: kudl
    url: jdbc:mysql://127.0.0.1:3306/kudlwork?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  output:
    ansi:
      enabled: ALWAYS
  profiles:
    include:
      - aws
      - okta
#  redis:
#    host: localhost
#    port: 6379

graphql:
  spqr:
    gui:
      enabled: true

app:
  connect-timeout: 500ms
  description: ${app.name} sample
  name: Properties Sample
  read-timeout: 10s
  security:
    enabled: true
    password: 123456
    permissions:
      CAN_DELETE_POSTS: false
      CAN_DELETE_USERS: false
      CAN_EDIT_POSTS: true
      CAN_EDIT_USERS: true
      CAN_VIEW_POSTS: true
      CAN_VIEW_USERS: true
    roles: 'USER,ADMIN,PARTNER   # List Property'
    username: callicoder
  upload-dir: /uploads
