app:
  connect-timeout: 500ms
  description: ${app.name} is a spring boot app that demonstrates how to use external
    configuration properties
  name: ConfigurationPropertiesDemoApp
  read-timeout: 10s
  security:
    enabled: true
    password: 123456
    permissions:
      CAN_DELETE_POSTS: false
      CAN_DELETE_USERS: false
      CAN_EDIT_POSTS: true
      CAN_EDIT_USERS: true
      CAN_VIEW_POSTS: true
      CAN_VIEW_USERS: true
    roles: 'USER,ADMIN,PARTNER   # List Property'
    username: callicoder
  upload-dir: /uploads
logging:
  level:
    root: INFO
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: kudl
    url: jdbc:mysql://127.0.0.1:3306/kudlwork?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kudl
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      format_sql: true
    open-in-view: false
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    include:
      - aws
#  redis:
#    host: localhost
#    port: 6379
